# This file was generated by GoReleaser. DO NOT EDIT.
cask "e2engine" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "4b5011f0a6bc41c201cd7ae531949cc7a2ab03cfd0f89eb8c75a166c62fd6c3b"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Darwin_arm64.tar.gz"
      rename "e2engine_Darwin_arm64/e2engine", "e2engine"
    end
    on_intel do
      sha256 "e04ca5fbdbb0c722e411c5d8cb9bb6d82f1926d6c9c76656acc383c91b69aa70"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Darwin_x86_64.tar.gz"
      rename "e2engine_Darwin_x86_64/e2engine", "e2engine"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd1548478c078f1d613145dd0be6545b4bafd119a65b5dcf18636750a73b576f"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Linux_arm64.tar.gz"
      rename "e2engine_Linux_arm64/e2engine", "e2engine"
    end
    on_intel do
      sha256 "c8c2e9eea766f7eedc83ab9eb64b77f313a347018d118a121e94d28f903705e4"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Linux_x86_64.tar.gz"
      rename "e2engine_Linux_x86_64/e2engine", "e2engine"
    end
  end

  name "e2engine"
  desc "Declarative end-to-end testing and service mocking for distributed systems."
  homepage "https://github.com/e2engine/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "e2engine"

  # No zap stanza required
end
