# This file was generated by GoReleaser. DO NOT EDIT.
cask "e2engine" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ce4058c0ac3d7b04740cfef5b4afb81723a1a3d2530380231a61036de98c3dbf"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Darwin_arm64.tar.gz"
      rename "e2engine_Darwin_arm64/e2engine", "e2engine"
    end
    on_intel do
      sha256 "cd968037f4e7691ce124859e2d3c5f55cadd0fd90841081fd04c76c18868f0d6"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Darwin_x86_64.tar.gz"
      rename "e2engine_Darwin_x86_64/e2engine", "e2engine"
    end
  end
  on_linux do
    on_arm do
      sha256 "f59a72b5e75015787371147ace215b10c1e3f758113c9ef1febf61cac2fb9db1"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Linux_arm64.tar.gz"
      rename "e2engine_Linux_arm64/e2engine", "e2engine"
    end
    on_intel do
      sha256 "44bb21903a81d9ff834c92703c95a2878b03d14e9762c53ad59f91122a18d9f2"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Linux_x86_64.tar.gz"
      rename "e2engine_Linux_x86_64/e2engine", "e2engine"
    end
  end

  name "e2engine"
  desc "Declarative end-to-end testing and service mocking for distributed systems."
  homepage "https://github.com/e2engine/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "e2engine"

  # No zap stanza required
end
