# This file was generated by GoReleaser. DO NOT EDIT.
cask "e2engine" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "a11a576caec88061fbbdec3b21b27e556c985eac8a11879383262833432308f6"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Darwin_arm64.tar.gz"
      rename "e2engine_Darwin_arm64/e2engine", "e2engine"
    end
    on_intel do
      sha256 "cc400f10b19d7a873f4b857ed20e8cbb5fb8d87b627788d058613aa7eb7dd9f8"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Darwin_x86_64.tar.gz"
      rename "e2engine_Darwin_x86_64/e2engine", "e2engine"
    end
  end
  on_linux do
    on_arm do
      sha256 "6fba07fca3ff49d8f85d5f66818dd64f6a5b14c290967bb021b2ce5e235382af"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Linux_arm64.tar.gz"
      rename "e2engine_Linux_arm64/e2engine", "e2engine"
    end
    on_intel do
      sha256 "8d2dead8765aad76fc309f2302d9717e4607100b3a51beb4e66756f4e1c0e1ea"
      url "https://github.com/e2engine/cli/releases/download/v#{version}/e2engine_Linux_x86_64.tar.gz"
      rename "e2engine_Linux_x86_64/e2engine", "e2engine"
    end
  end

  name "e2engine"
  desc "Declarative end-to-end testing and service mocking for distributed systems."
  homepage "https://github.com/e2engine/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "e2engine"

  # No zap stanza required
end
