# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Declarative end-to-end testing and service mocking for distributed systems."
  homepage "https://github.com/e2engine/cli"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e2engine/cli/releases/download/v0.0.2/cli_Darwin_x86_64.tar.gz"
      sha256 "0cadfdb5692ff0997c181859d868b61d9cb0681c6a5196509ea5612f9dd95cd0"

      define_method(:install) do
        bin.install "e2engine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e2engine/cli/releases/download/v0.0.2/cli_Darwin_arm64.tar.gz"
      sha256 "80bd6307cfe318140108d3735c2ac233743ab6da879053be234dafdff9b51e1a"

      define_method(:install) do
        bin.install "e2engine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e2engine/cli/releases/download/v0.0.2/cli_Linux_x86_64.tar.gz"
      sha256 "c36328ab9d8f939ecc702a5ceaaa51fe5183d931d84a6b7a3c852652dbbc2673"
      define_method(:install) do
        bin.install "e2engine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e2engine/cli/releases/download/v0.0.2/cli_Linux_arm64.tar.gz"
      sha256 "eb46d392ae6d07f93b626497f8b9803bdde5251a4a1794aa292c6cb7c098e7d0"
      define_method(:install) do
        bin.install "e2engine"
      end
    end
  end
end
